=== PrincyM/SimpleXML-ECommerce-Support-Ticket-System/tickets.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tickets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ticket" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="issueDate" type="xs:date" />
                            <xs:element name="status" type="xs:string" />
                            <xs:element name="issueCategory" type="xs:string" />
                            <xs:element name="clientId" type="xs:integer" />
                            <xs:element name="messages">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="message" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:integer">
                                                        <xs:attribute name="userId" type="xs:integer" />
                                                        <xs:attribute name="supportStaffId" type="xs:integer" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="dated" type="xs:date" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <!--<xs:element name="supportStaffMessage" maxOccurs="unbounded">-->
                                            <!--<xs:complexType>-->
                                                <!--<xs:simpleContent>-->
                                                    <!--<xs:extension base="xs:string">-->
                                                        <!--<xs:attribute name="dated" type="xs:date" use="required" />-->
                                                    <!--</xs:extension>-->
                                                <!--</xs:simpleContent>-->
                                            <!--</xs:complexType>-->
                                        <!--</xs:element>-->
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="ticketId" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- CUSTOM TYPES -->
    <xs:simpleType name="staffId">
        <xs:restriction base="xs:string">
            <xs:pattern value="SS\d{2}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ticketId">
        <xs:restriction base="xs:integer">
            <xs:pattern value="\d{3}" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== PrincyM/SimpleXML-ECommerce-Support-Ticket-System/tickets.xml
<?xml version="1.0" encoding="utf-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tickets.xsd">
    <ticket id="201">
         <issueDate>2018-01-07</issueDate>
         <status>Resolved</status>
         <issueCategory>Order Question</issueCategory>
         <clientId>5001</clientId>
         <messages>
             <message userId="5001" dated="2018-01-07" time="06:01:57pm">
                When would I receive my order?
            </message>
             <message userId="1004" dated="2018-01-08" time="10:01:57am">
                Thank you for contacting us about your order. Can I have the order ID so that we can investigate further?
            </message>
         <message userId="5001" dated="2018-03-29" time="10:44:26pm">Hello there</message><message userId="5001" dated="2018-03-29" time="10:48:50pm">How are you</message><message userId="1004" dated="2018-03-29" time="11:37:53pm">Were you able to receive an answer? </message></messages>
    </ticket>
    <ticket id="202">
         <issueDate>2018-01-29</issueDate>
         <status>New</status>
         <issueCategory>Shipping</issueCategory>
         <clientId>5003</clientId>
         <messages>
             <message userId="5003" dated="2018-01-29" time="09:01:57am">
                When will my order number: 10006 be shipped?
            </message>
             <message userId="1023" dated="2018-01-30" time="09:01:57pm">
                Thank you for contacting us about your order: 10006. Your order will be shipped in the next 24 hours
            </message>
         </messages>
    </ticket>
    <ticket id="203">
         <issueDate>2018-02-14</issueDate>
         <status>Resolved</status>
         <issueCategory>Product Availability</issueCategory>
         <clientId>5004</clientId>
         <messages>
             <message userId="5004" dated="2018-02-14" time="07:01:57am">
                Is this top still available?
            </message>
             <message userId="1023" dated="2018-02-15" time="12:01:57pm">
                Thank you for contacting us. Could you please specify which product with a product link or ID?
            </message>
         </messages>
     </ticket>
<ticket id="340"><issueDate>2018-03-29</issueDate><status>In Progress</status><issueCategory>Shipping</issueCategory><clientId>1004</clientId><messages><message userId="1004" dated="2018-03-29" time="11:22:44pm">Hello there</message></messages></ticket><ticket id="340"><issueDate>2018-03-29</issueDate><status>New</status><issueCategory>Shipping</issueCategory><clientId>1004</clientId><messages><message userId="1004" dated="2018-03-29" time="11:32:03pm">Hello there</message></messages></ticket></tickets>
