=== PrincyM/SimpleXML-ECommerce-Support-Ticket-System/users.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first" type="xs:string" />
                                        <xs:element name="middle" type="xs:string" minOccurs="0" />
                                        <xs:element name="last" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="username" type="xs:string" />
                            <xs:element name="password" type="xs:string" />
                            <xs:element name="location">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="city" type="xs:string" />
                                        <xs:element name="province" type="provinceList" />
                                        <xs:element name="country" type="xs:string" />
                                        <xs:element name="zipCode" type="zip" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="role" type="roletype" use="required" />
                        <xs:attribute name="id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- CUSTOM TYPES -->
    <xs:simpleType name="provinceList">
      <xs:restriction base="xs:string">
        <xs:enumeration value="Ontario" />
        <xs:enumeration value="British Columbia" />
        <xs:enumeration value="Quebec" />
        <xs:enumeration value="Alberta" />
        <xs:enumeration value="Manitoba" />
        <xs:enumeration value="New Brunswick" />
        <xs:enumeration value="Newfoundland and Labrador" />
        <xs:enumeration value="Northwest Territories" />
        <xs:enumeration value="Nova Scotia" />
        <xs:enumeration value="Nunavut" />
        <xs:enumeration value="Prince Edward Island" />
        <xs:enumeration value="Saskatchewan" />
        <xs:enumeration value="Yukon" />
     </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="zip">
      <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z][0-9][a-zA-Z][0-9][a-zA-Z][0-9]" />
     </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="roletype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="client" />
      <xs:enumeration value="staff" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== PrincyM/SimpleXML-ECommerce-Support-Ticket-System/users.xml
<?xml version="1.0" encoding="utf-8" ?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="users.xsd">
    <user role="client" id="5001">
     <name>
        <first>Jaime</first>
        <last>Hardy</last>
     </name>
     <username>JaimeH</username>
     <password>jaime003</password>
     <location>
        <city>Toronto</city>
        <province>Ontario</province>
        <country>Canada</country>
        <zipCode>L6T2M5</zipCode>
     </location>
    </user>
    <user role="staff" id="1004">
     <name>
        <first>Kelly</first>
        <middle>T</middle>
        <last>Peterson</last>
     </name>
     <username>KellyP</username>
     <password>kelly006</password>
     <location>
        <city>Vancouver</city>
        <province>British Columbia</province>
        <country>Canada</country>
        <zipCode>V5H3Z7</zipCode>
     </location>
    </user>
    <user role="client" id="5003">
     <name>
        <first>Candice</first>
        <last>Porter</last>
     </name>
     <username>CandiceP</username>
     <password>candice009</password>
     <location>
        <city>Montreal</city>
        <province>Quebec</province>
        <country>Canada</country>
        <zipCode>H1A0A1</zipCode>
     </location>
    </user>
    <user role="staff" id="1023">
        <name>
            <first>Dianne</first>
            <middle>K</middle>
            <last>Walton</last>
        </name>
        <username>DianneW</username>
        <password>dianne012</password>
        <location>
            <city>Toronto</city>
            <province>Ontario</province>
            <country>Canada</country>
            <zipCode>L6T2M5</zipCode>
        </location>
    </user>
    <user role="client" id="5004">
        <name>
            <first>Rita</first>
            <last>Stephens</last>
        </name>
        <username>RitaP</username>
        <password>rita015</password>
        <location>
            <city>Montreal</city>
            <province>Quebec</province>
            <country>Canada</country>
            <zipCode>H1B0A2</zipCode>
        </location>
    </user>
</users>
